vim.opt.autoread = true                          -- Reload a file when changed from outside
vim.opt.autowrite = true                         -- Write when we leave the buffer
vim.opt.backup = false                           -- creates a backup file
vim.opt.backspace = "eol,indent,start"           -- backspace behaves as expected
vim.opt.clipboard = "unnamedplus"                -- allows neovim to access the system clipboard
vim.opt.cmdheight = 2                            -- more space in the neovim command line for displaying messages
vim.opt.completeopt = { "menuone", "noinsert", "noselect" }  -- mostly just for cmp
vim.opt.conceallevel = 0                         -- so that `` is visible in markdown files
vim.opt.fileencoding = "utf-8"                   -- the encoding written to a file
vim.opt.hlsearch = false                         -- don't highlight all matches on previous search pattern
vim.opt.incsearch = true                         -- Move cursor to the matched string while typing the pattern
vim.opt.inccommand = "nosplit"                   -- Show live results of :s
vim.opt.gdefault = true                          -- Toggle g by default in substitutions
vim.opt.ignorecase = true                        -- ignore case in search patterns
vim.opt.smartcase = true                         -- smart case
vim.opt.diffopt = "iwhite,vertical"              -- In diff mode, open the buffers vertically, and ignore whitespace changes.
vim.opt.mouse = "a"                              -- allow the mouse to be used in neovim
vim.opt.pumheight = 10                           -- pop up menu height
vim.opt.showmode = true                          -- Display -- INSERT -- and co
vim.opt.showcmd = true                           -- Show command being executed
vim.opt.showtabline = 2                          -- always show tabs
vim.opt.autoindent = true                        -- make indenting smarter again
vim.opt.cinoptions="(0,W4,u0,U0,t0,g1,h1,N-s,>s" -- see :help cinoptions-values
vim.opt.timeoutlen = 300                         -- time to wait for a mapped sequence to complete (in milliseconds)
vim.opt.undofile = true                          -- enable persistent undo
vim.opt.undolevels = 1000                        -- number of undos to save
vim.opt.undoreload = 100000                      -- max size of file to save for undo
vim.opt.undodir = vim.fn.expand('~/.vim/undo')   -- undo folder
vim.opt.updatetime = 500                         -- faster completion (4000ms default)
vim.opt.writebackup = false                      -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
vim.opt.expandtab = true                         -- convert tabs to spaces
vim.opt.smarttab = true                          -- When tabbing manually, use shiftwidth instead of tabstop and softtabstop
vim.opt.shiftwidth = 2                           -- the number of spaces inserted for each indentation
vim.opt.softtabstop = 2                          -- the number of spaces when pressing tab
vim.opt.tabstop = 8                              -- a tab character is 8 spaces.
vim.opt.cursorline = true                        -- highlight the current line
vim.opt.number = true                            -- set numbered lines
vim.opt.signcolumn = "yes"                       -- always show the sign column, otherwise it would shift the text each time
vim.opt.wrap = true                              -- display lines as one long line
vim.opt.linebreak = true                         -- companion to wrap, don't split words
vim.opt.breakindent = true                       -- (This and next 2): when wrapping, prepend ".." to the line.
vim.opt.breakindentopt = "sbr"
vim.opt.showbreak = ".."
vim.opt.scrolloff = 8                            -- minimal number of screen lines to keep above and below the cursor
vim.opt.shortmess = "aOtTc"                      -- flags to shorten vim messages, see :help 'shortmess'
vim.opt.runtimepath:remove("/usr/share/vim/vimfiles")  -- separate vim plugins from neovim in case vim still in use
vim.opt.laststatus = 2                           -- Always show status line
vim.opt.statusline = [[%f %l|%c %m %#warningmsg#%*%=%p%% (%Y%R)]] -- Status line format.
vim.opt.wildmenu = true                          -- Command line completion
vim.opt.wildmode = "list:longest:full"           -- See :help wildmode
vim.opt.visualbell = false                       -- Disable visual bell
vim.opt.vb = true                                -- Disable visual bell
vim.opt.showmatch = true                         -- Briefly show matching braces, parens, etc
vim.opt.foldenable = false                       -- Disable folds.
vim.opt.comments = "s0:/*,mb:**,ex:*/,://"
vim.opt.list = true                              -- Show tabs and trailing spaces.
vim.opt.listchars = "tab:>-,trail:."
