source $HOME/.zshrc-generic
alias shutdown="sudo shutdown -hP now"
alias suspend="gnome-screensaver-command -l"
alias ls="ls -phG --color"

xmodmap $HOME/.Xmodmap

evince () { `/usr/bin/evince "$1" > /dev/null 2>&1 &` ;}
