source $HOME/.zshrc-generic
alias shutdown="sudo shutdown -hP now"
alias suspend="gnome-screensaver-command -l"
alias aquarium=asciiquarium
alias ls="ls -phG --color"
alias jogsoul="$SCRIPTS/jogsoul.pl"

evince () { `/usr/bin/evince "$1" > /dev/null 2>&1 &` ;}
